---
- name: Start powerjoular
  hosts: workers
  remote_user: gsd
  
  tasks:
  - name: make sure service is not running
    become: yes
    ansible.builtin.service:
        name: powerjoular.service
        state: stopped
        
  - name: Remove energy file
    become: yes
    ansible.builtin.file:
        path: /tmp/powerjoular-service.csv
        state: absent

  - name: Start powerjoular service
    become: yes
    ansible.builtin.service:
        name: powerjoular.service
        state: started
