---
- name: Stop powerjoular
  hosts: workers
  remote_user: gsd
  
  tasks:
  - name: stop powerjoular service
    become: yes
    ansible.builtin.service:
        name: powerjoular.service
        state: stopped
